[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'No build step required - static site with serverless functions'"

[build.environment]
  NODE_VERSION = "20"

# Redirect all API calls to Netlify Functions
# IMPORTANT: More specific patterns must come FIRST
[[redirects]]
  from = "/api/search-artist"
  to = "/.netlify/functions/search-artist"
  status = 200
  force = true

[[redirects]]
  from = "/api/artist/*/releases"
  to = "/.netlify/functions/artist-releases"
  status = 200
  force = true

[[redirects]]
  from = "/api/artist/*/similar"
  to = "/.netlify/functions/artist-similar"
  status = 200
  force = true

[[redirects]]
  from = "/api/artist/*"
  to = "/.netlify/functions/artist"
  status = 200
  force = true

[[redirects]]
  from = "/api/release/*/recordings"
  to = "/.netlify/functions/release-recordings"
  status = 200
  force = true

# SPA fallback - redirect all non-file requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

